# Generated by Django 3.1.1 on 2020-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200914_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('sdes', models.TextField(null=True)),
                ('long_des', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
